# Generated by Django 3.2.6 on 2021-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalwebapp', '0002_producttable4_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable4',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
